New serverless pattern - apigw-lambda-bedrock-sam
aws-samples/serverless-patterns pull request #1695
Opened 2023-09-30 13:48 UTC by sushir-vr

*Issue #, if available:*

*Description of changes:*
This pattern creates an API Gateway REST API with Lambda proxy integration which places invoke calls to Amazon Bedrock for text and image generation.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-10-11 11:27 UTC, sushir-vr commented
Fixed validity check errors

2023-10-15 12:18 UTC, boyney123 commented
Hey,

Looks like this branch has merge conflicts? Any chance you can take a look at them?

2023-10-15 12:22 UTC, boyney123 requested changes

2023-10-15 12:22 UTC, boyney123 commented on apigw-lambda-bedrock-sam/example-pattern.json
> +      "linkedin": "www.linkedin.com/in/abha-tripathi-344a0a146"
```suggestion
      "linkedin": "abha-tripathi-344a0a146"
```

2023-10-15 12:22 UTC, boyney123 commented on apigw-lambda-bedrock-sam/example-pattern.json
> +      "linkedin": "www.linkedin.com/in/sushirvr"
```suggestion
      "linkedin": "sushirvr"
```

2023-10-15 13:19 UTC, closed without merging