New serverless pattern - apigw-openapi-lambda-dynamodb-xray-terraform
aws-samples/serverless-patterns pull request #1718
Opened 2023-10-06 22:03 UTC by nikhilswagle

*Issue #, if available:*

*Description of changes:*
This pattern demonstrates how to deploy an API Gateway REST API with Lambda backend integration that is defined in an OpenAPI specification format using Terraform. The pattern also shows how backend Lambda is integrated with Lambda powertools for logging and more importantly tracing the requests end to end from API Gateway to DynamoDB data store.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-10-23 17:05 UTC, singledigit requested changes
There are several problems with this pattern.

1. There is not an `example-pattern.json` file in the root.
2. We are having users run a deploy script. This is not a preferred method. We have several options. Either use the serverless.tf modules or have TF run the script.

Please refactor and add an example-pattern file.

2023-10-31 05:18 UTC, nikhilswagle commented
Requested changes have been made.

Thanks,
Damodar

2023-11-17 05:10 UTC, singledigit approved these changes

2023-11-17 05:10 UTC, singledigit commented on apigw-openapi-lambda-dynamodb-xray-terraform/example-pattern.json
> +  "title": "Deploying API Gateway REST API using OpenAPI spec with Lambda Powertools",
```suggestion
  "title": "Amazon API Gateway to AWS Lambda using OpenAPI",
```

2023-11-17 05:10 UTC, singledigit commented on apigw-openapi-lambda-dynamodb-xray-terraform/example-pattern.json
> +      "linkedin": "www.linkedin.com/in/damodar-shenvi-wagle-72375548"
```suggestion
      "linkedin": "damodar-shenvi-wagle-72375548"
```

2023-11-17 05:10 UTC, merged