New serverless pattern: ApiGateway-Lambda-Bedrock using AWS SDK for Java
aws-samples/serverless-patterns pull request #1919
Opened 2023-11-27 15:19 UTC by kozub

*Issue #, if available:* https://github.com/aws-samples/serverless-patterns/issues/1880

*Description of changes:*

This pattern will create an ApiGateway-Lambda_Bedrock demonstrating AWS SDK for Java usage.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-01-02 19:53 UTC, kozub commented
Hello Team, do you have any updates related to this PR? Please let me know if there is anything that I need to fix.

2024-01-04 15:06 UTC, ellisms requested changes
Just a few minor changes.

2024-01-04 15:06 UTC, ellisms commented on apigw-lambda-bedrock-cdk-java/infrastructure/src/main/java/com/example/InfrastructureStack.java
> +        Function lambdaFunction = Function.Builder.create(this, "LambdaBedrockFunction")
Suggest explicitly adding the CW Logs group as a resource so it can be cleaned up when deleting the stack.

2024-01-04 16:03 UTC, kozub commented
> Just a few minor changes.

Thank you for your review. I've just published a commit with requested changes.

2024-01-04 18:29 UTC, ellisms approved these changes

2024-01-04 18:46 UTC, merged