New Serverless Pattern : AWS lambda and Amazon Bedrock integration
aws-samples/serverless-patterns pull request #1977
Opened 2023-12-22 03:15 UTC by nj80750

*Issue #, if available:*

*Description of changes:*
This pattern will use Amazon Bedrock and AWS Lambda function to show how to develop a GenAI application with minimum code. With this design, customers will be able to choose their preferred Foundation Model from the Amazon Bedrock

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-01-03 09:26 UTC, parikhudit commented
taking a look

2024-01-05 08:20 UTC, parikhudit commented
Suggestion: You may want to add a note in README file that the mentioned subnets need to be private and have internet access via NAT Gateway. Alternatively, you may alter the solution to create interface endpoint for bedrock or remove Lambda - VPC association.

2024-01-05 08:26 UTC, parikhudit commented on terraform-lambda-bedrock-integration/README.md
> +Optionally, you can also specify foundation model name, env and organization (tagging purposes), timeout and memory_size (AWS Lmabda function compute purposes) and lastly logging_level to specify the
Typo: 'Lmabda' -> 'Lambda'

2024-01-05 08:27 UTC, parikhudit requested changes
Suggestion: You may want to add a note in README file that the mentioned subnets need to be private and have internet access via NAT Gateway. Alternatively, you may alter the solution to create interface endpoint for bedrock or remove Lambda - VPC association.

2024-01-07 08:13 UTC, merged

2024-01-09 08:58 UTC, bls20AWS commented
will go live in 24 hours on: https://serverlessland.com/patterns/terraform-lambda-bedrock-integration

2024-01-10 23:15 UTC, nj80750 commented
Hi @bls20AWS  is it live yet ?