Serverless pattern eventbridge pipe sqs stepfunctions filter transform cdk python
aws-samples/serverless-patterns pull request #1994
Opened 2023-12-30 16:18 UTC by manikandanks2000

*Issue #, if available:*

*Description of changes:*
This pattern will use Amazon EventBridge Pipe to accept source messages from Amazon Simple Queue Service and will apply filter and transformation before sending the target message to AWS Step Functions.
This example project implemented with CDK/Python.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-01-03 10:39 UTC, pputhran commented
Can you please check the errors and re-submit please?

2024-01-05 04:18 UTC, manikandanks2000 commented
Fixed the errors on example pattern file and linkedin.  Let me know if you have any questions. Thanks

2024-01-06 16:44 UTC, manikandanks2000 reviewed
fixed the errors and resubmitted for git code review workflow for schema validation check.

2024-01-09 12:36 UTC, pputhran requested changes

2024-01-09 12:36 UTC, pputhran commented on cdk-sqs-eventbridge-pipes-stepfunctions--filter-transform-python/example-pattern.json
> +    }
Can you please take a look at the `projectFolder` and `templateFile` references? They seem to be incorrect.

2024-01-11 15:54 UTC, pputhran commented
@manikandanks2000 Did you get a chance to review the requested changes?

2024-01-12 17:32 UTC, manikandanks2000 commented
@pputhran  thanks for the input ..checking the changes, will confirm once complete soon.

2024-01-13 17:14 UTC, manikandanks2000 commented
@pputhran  Let me know if the changes are good to move forward. thanks

2024-01-13 23:10 UTC, closed without merging