New servereless pattern eventbridge-pipes-amq-to-redshift
aws-samples/serverless-patterns pull request #2051
Opened 2024-01-17 01:13 UTC by vinodh-aws

*Issue #2052 

*Description of changes:*
Description of changes:
This pattern demonstrates how to send messages from Amazon MQ for ActiveMQ queue to Amazon Redshift cluster using Amazon EventBridge Pipes and utilizing Amazon Redshift data API queries as target.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-01-19 19:48 UTC, ellisms requested changes
Minor suggested changes.

2024-01-19 22:19 UTC, vinodh-aws commented on eventbridge-pipes-sqs-to-redshift/example-pattern.json
> +  "authors": [
Hi ellisms@  

Yes, I'm helping Rajat as a part of Messaging Focus Area

2024-01-24 20:15 UTC, vinodh-aws commented
Hi ellisms@ Checking you have any further questions in this request ?

2024-01-24 21:17 UTC, ellisms commented
Hi @vinodh-aws  - no additional questions. I'll start working on the pre-publishing tasks. Thanks!

2024-02-20 09:55 UTC, boyney123 commented
Looks like the pull request has merge conflicts, can you resolve these? Thanks!

2024-02-20 17:57 UTC, ellisms commented
@boyney123 Can you try now? If you still get a conflict on that file I think we can drop it completely, the serverlessland json to use file is `eventbridge-pipes-amq-to-redshift-cdk-python/ebpipes-amq-redshift-cdk-python.json`

2024-03-04 15:35 UTC, merged