New serverless pattern - apigw-http-api-lambda-ts-cdk
aws-samples/serverless-patterns pull request #2199
Opened 2024-03-24 09:21 UTC by philippewanner

# apigw-http-api-lambda-ts-cdk

## Description

This pattern create an Amazon API Gateway HTTP API and a dummy Lambda function returning a simple "Hello World".

## Language
Node.js (Typescript)

## Framework
CDK

## Service from/to
Service from: API Gateway HTTP API (v2)
Service to: Lambda

## Description
This pattern creates an Amazon API Gateway HTTP API (v2) that integrates with an AWS Lambda function by using AWS Cloud Development Kit (AWS CDK).

Amazon API Gateway HTTP API is designed with minimal features so it can be offered at a lower price than the REST API. For more information, please read the official document [Choosing between REST APIs and HTTP APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html).

This pattern deploys a API Gateway HTTP API that is responsible to route the root path ("/") to the AWS Lambda function. The function (called 'dummy') return a 200 HTTP code and "Hello World" payload to the caller.

The template includes a CDK stack a HTTP API and a Lambda resources. The stack will output the HTTP API URL after the deployment, so you can test the API.

## Deployment commands
npm run deploy

## Payload example (e.g. Lambda event payload from source service).

N/A

## Additional resources (optional: link and anchor text, up to 5 resources)

    [Working with the AWS CDK in TypeScript](https://docs.aws.amazon.com/cdk/v2/guide/work-with-cdk-typescript.html)
    [Working with HTTP APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api.html)
    [Building Lambda functions with TypeScript](https://docs.aws.amazon.com/lambda/latest/dg/lambda-typescript.html)

## Author bio

Name: Philippe Wanner
Photo URL: https://www.linkedin.com/in/philippe-wanner/
LinkedIn: https://www.linkedin.com/in/philippe-wanner/
Twitter handle: n/a
Description (up to 255 chars): Philippe is a Senior Specialist Solutions Architect at Amazon Web Services based in Zurich, Switzerland. His role is to spread the migration and modernization best practices for large organisations. 
[Follow on LinkedIn](https://www.linkedin.com/in/philippe-wanner/)

2024-04-04 17:49 UTC, ellisms requested changes
Hi @philippewanner - thanks for the submission. Requesting a few changes before we can proceed.

2024-04-04 17:49 UTC, ellisms commented on apigw-http-api-lambda-ts-cdk/README.md
> +If Amazon API Gateway HTTP API (v2) covers all the features' requirements, it's recommended to use HTTP API (v2) over REST API (v1). The HTTP API has the advantage to be significantly less expensive,
Can you quantify the savings and performance? As written, the statement is vague.

2024-04-04 17:49 UTC, ellisms commented on apigw-http-api-lambda-ts-cdk/README.md
> +## Requirements
From my test, it looks like docker is also required. I would add it to the list.

2024-04-04 17:49 UTC, ellisms commented on apigw-http-api-lambda-ts-cdk/README.md
> +1. CDK will provision an Amazon Gateway API HTTP API and a dummy Lambda function.
```suggestion
1. CDK will provision an Amazon API Gateway HTTP API and a sample Lambda function.
```

2024-04-04 17:49 UTC, ellisms commented on apigw-http-api-lambda-ts-cdk/README.md
> +2. It will integrate the Lambda function to the  HTTP API with the route "/"
```suggestion
2. It will integrate the Lambda function with the  HTTP API using the route "/"
```

2024-04-09 10:30 UTC, philippewanner commented
The file example-pattnern.json has been added as requested

2024-04-17 17:04 UTC, merged