update `cdk-sfn-s3` pattern to cdk v2
aws-samples/serverless-patterns pull request #2335
Opened 2024-06-23 19:15 UTC by garysassano

*Issue #, if available:*

*Description of changes:*

Updated the code to use CDK v2 libs.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-01 19:35 UTC, pputhran requested changes
can you also add example-pattern.json?

[example](https://github.com/aws-samples/serverless-patterns/blob/main/_pattern-model/example-pattern.json)

2024-07-17 10:20 UTC, pputhran commented on cdk-sfn-s3/example-pattern.json
> +      "templateFile": "src/lib/cdk-sfn-s3-stack.ts"
Running into an error on validating this file. Can you please remove the projectFolder value from the templateFile?

Simple fix would be to rename the `cdk-sfn-s3-stack.ts` to something else and update the `templateFile` value

2024-12-19 20:08 UTC, garysassano commented
How many months does it usually take for PRs to get merged?

2025-01-17 16:56 UTC, garysassano commented on cdk-sfn-s3/example-pattern.json
> +      "templateFile": "src/lib/cdk-sfn-s3-stack.ts"
I know it's been half a year, but could you please take a moment to review the PR?

2025-01-27 08:09 UTC, parikhudit commented
Thanks for the contribution @garysassano, appreciate your ownership in updating existing pattern.
Just a heads up that I've reverted the author name in ```example-pattern.json``` to be of initial author. We do not generally add new author to the pattern, unless there's a major revamp or the pattern is re-written.

2025-03-24 10:55 UTC, merged