Add s3-eventbridge-sfn-terraform patterrn
aws-samples/serverless-patterns pull request #2362
Opened 2024-07-08 07:51 UTC by enmata

*Issue #, if available:*
Adding s3-eventbridge-sfn-terraform patterrn

*Description of changes:*
Adding terraform version of s3-eventbridge-sfn pattern
https://serverlessland.com/patterns/s3-eventbridge-wildcard-sam

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-29 07:18 UTC, enmata commented
Added example-pattern.json

2024-08-02 12:06 UTC, ellisms requested changes
@enmata Thanks for the submission. Requesting a few minor edits.

2024-08-07 11:44 UTC, enmata commented on s3-eventbridge-sfn-terraform/README.md
> +## Cleanup
ok

2024-08-07 11:44 UTC, enmata commented on s3-eventbridge-sfn-terraform/README.md
> +# S3 to StepFunctions with EventBridge Rule
ok

2024-08-07 11:44 UTC, enmata commented on s3-eventbridge-sfn-terraform/README.md
> +This pattern demonstrates how to create an EventBridge rule with S3 as the event source and Step Functions as target. Implemented with Terraform.
ok

2024-08-07 11:44 UTC, enmata commented on s3-eventbridge-sfn-terraform/README.md
> +- This will send an `Object Created` event to EventBridge
ok

2024-08-07 11:44 UTC, enmata commented on s3-eventbridge-sfn-terraform/README.md
> +1. Navigate to AWS console and go to the S3 bucket that was created by this terraform template
ok

2024-08-07 11:44 UTC, enmata commented on s3-eventbridge-sfn-terraform/README.md
> +3. Immediately after the upload is completed successfully, navigate to the Step Functions state machine, you will see an execution has been triggered
ok

2024-08-07 11:44 UTC, enmata commented on s3-eventbridge-sfn-terraform/README.md
> +To create a full Step Functions workflow with the pattern created, you can find out example workflows at Step Functions Workflow: [serverlessland.com/workflows](https://serverlessland.com/workflows)
ok

2024-08-07 11:44 UTC, enmata commented on s3-eventbridge-sfn-terraform/README.md
> +## Documentations and next step
ok

2024-08-07 11:45 UTC, enmata commented
Requested changes applied. Please, check again when yo have the chance.

2024-08-07 13:22 UTC, ellisms commented
Thanks @enmata . I'll put this in the publishing queue.

2024-08-07 13:26 UTC, merged