New serverless pattern - appsync-private-api-sam
aws-samples/serverless-patterns pull request #2367
Opened 2024-07-09 09:12 UTC by Tessot

Issue #, if available:

Description of changes: This pattern shows how you can deploy an AWS AppSync Private API which can only be invoked by resources within your private network.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-26 14:22 UTC, pputhran requested changes

2024-07-26 14:22 UTC, pputhran commented on appsync-private-api-sam/example-pattern.json
> +  "language": "Yaml",
This should be YAML (uppercase)

2024-09-11 06:29 UTC, bfreiberg requested changes

2024-09-11 06:29 UTC, bfreiberg commented on appsync-private-api-sam/README.md
> +API Key is used as the authorization mode for the AppSync API however it is not recommended to use API Key for production application, kindly refer to other authorization modes supported by AppSync i
```suggestion
API Key is used as the authorization mode for the AppSync API. However it is not recommended to use API Key for production application, please refer to other authorization modes supported by AppSync in the [documentation](https://docs.aws.amazon.com/appsync/latest/devguide/security-authz.html)
```

2024-09-11 06:29 UTC, bfreiberg commented on appsync-private-api-sam/README.md
> +You can easily test this pattern using any command prompt that supports the `curl` command. Refer to the outputs `AppSyncApiUrl`, `AppSyncApiKey` and `AppSyncVPCEndpointDNS` from deploying the SAM ap
```suggestion
You can test this pattern using any command prompt that supports the `curl` command. Refer to the outputs `AppSyncApiUrl`, `AppSyncApiKey` and `AppSyncVPCEndpointDNS` from deploying the SAM application which will be used for testing.
```

2024-09-11 06:29 UTC, bfreiberg commented on appsync-private-api-sam/README.md
> +-- Using AppSync VPC Interface Endpoint DNS (you will need to pass the`AppSyncGraphQLAPIURL` in the host header, remember to remove suffix `www.`)
Do you mean prefix instead?

2024-10-08 07:26 UTC, bfreiberg commented
Hi, do you still plan to address the requested changes?

2024-10-22 09:20 UTC, closed without merging

2024-10-22 09:20 UTC, Tessot commented
I will be creating a new pull request with the changes