New serverless pattern - EventBridge-Bedrock-S3-AOSS
aws-samples/serverless-patterns pull request #2381
Opened 2024-07-15 13:15 UTC by rajavaid77

*Issue #, if available:*

*Description of changes:*

Added a serverless pattern to automate syncing data sources for Amazon Bedrock Knowledgebases using EventBridge scheduler. An EventBridge schedule is configured to run at a regular rate (default of 5mins). The EventBridge uses the universal target to trigger the StartIngestionJob API on the Amazon Bedrock Agent service.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-17 12:08 UTC, pputhran requested changes
Running into an error on deployment.
BedrockServiceRoleAccessPolicyStack and OpenSearchServerlessStack got deployed successfully.

BedrockKnowledgebaseStack is failing with the folliwing error

Resource handler returned message: "bedrock-rag-jcrob6 already exists (Service: S3, Status Code: 0, Request ID: null)" (RequestToken: f84ae2ac-9ac4-ad30-44c1-4a2c0a9bb599, HandlerErrorCode: AlreadyExists)

2024-07-17 12:08 UTC, pputhran commented on eventbridge-bedrock-s3-aoss/template.yaml
Is this needed?

2024-07-19 00:58 UTC, rajavaid77 commented on eventbridge-bedrock-s3-aoss/example-pattern.json
> +      "templateFile": "eventbridge-lambda-bedrock_stack.py"
fixed. pls double check

2024-07-19 00:59 UTC, rajavaid77 commented on s3-lambda-bedrock-aoss/README.md
it was added by mistake. now removed. thanks for finding this..

2024-07-19 00:59 UTC, rajavaid77 commented on apigw-lambda-bedrock-s3-cdk-python/README.md
it was added by mistake. now removed. thanks for finding this..

2024-07-19 00:59 UTC, rajavaid77 commented on eventbridge-bedrock-s3-aoss/template.yaml
no. deleted

2024-07-19 00:59 UTC, rajavaid77 commented on eventbridge-bedrock-s3-aoss/README.md
> +    cdk deploy --all
fixed the errors.

2024-07-26 09:39 UTC, pputhran requested changes
Unfortunately ran into another error with the new changes with BedrockKBStack

2024-07-26 09:39 UTC, pputhran commented on eventbridge-bedrock-s3-aoss/README.md
> +    cdk deploy --all
Unfortunately ran into another error with the new changes with BedrockKBStack

Resource handler returned message: "Supplied Policy document is breaching Cloudwatch Logs policy length limit. (Service: CloudWatchLogs, Status Code: 400, Request ID: 39ff2d15-9eca-423f-bf0c-bf61d8d5bd4e)" (RequestToken: 972f5e1f-da40-7437-4d9b-5d6c5f5fea2e, HandlerErrorCode: AccessDenied)

2024-07-30 09:35 UTC, rajavaid77 commented
> Unfortunately ran into another error with the new changes with BedrockKBStack

This appears to be specific to a situation in the AWS account used for deploying the stack. Fixed by adding an explicitly policy that should solve the issue around limits.

2024-09-26 14:47 UTC, closed without merging