adding jwt cognito pattern for websocket api using lambda authorizer
aws-samples/serverless-patterns pull request #2384
Opened 2024-07-15 20:41 UTC by srajaw

*Issue #, if available:*

*Description of changes: So basically websocket api doesn't have JWT authorizer by default. This patterns creates a lambda authorizer which verifies the JWT token for cognito and sends a policy back to the websocket api based on valid or invalid token. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-23 13:06 UTC, marcojahn requested changes

2024-07-24 18:04 UTC, srajaw commented on jwt_authorizer_websocket_api_lambda_authorizer/template.yaml
> +  MyLambdaLayer:
this layer is for cognito token verification. removing the layer will make the main code look more complex. I would suggest to keep the layer.

2024-07-24 18:10 UTC, srajaw commented on jwt_authorizer_websocket_api_lambda_authorizer/src/sendMessage.zip
Sam only has two options, i.e., either provide s3 bucket uri or a local file, so local file has to be zipped before hand.

2024-07-29 09:43 UTC, marcojahn requested changes

2024-07-29 09:43 UTC, marcojahn commented on jwt_authorizer_websocket_api_lambda_authorizer/template.yaml
> +  MyLambdaLayer:
This is fine and I think creating a layer build process will just increase complexity here

2024-07-29 09:43 UTC, marcojahn commented on jwt_authorizer_websocket_api_lambda_authorizer/src/onConnect.zip
Pls add as source file and let AWS SAM handle the packaging, e.g.
https://github.com/aws/aws-sam-cli-app-templates/tree/master/python3.12/hello

2024-07-29 09:43 UTC, marcojahn commented on jwt_authorizer_websocket_api_lambda_authorizer/src/onDisconnect.zip
Pls add as source file and let AWS SAM handle the packaging, e.g.
https://github.com/aws/aws-sam-cli-app-templates/tree/master/python3.12/hello

2024-07-29 09:43 UTC, marcojahn commented on jwt_authorizer_websocket_api_lambda_authorizer/src/sendMessage.zip
Pls add as source file and let AWS SAM handle the packaging, e.g.
https://github.com/aws/aws-sam-cli-app-templates/tree/master/python3.12/hello

2024-07-29 09:43 UTC, marcojahn commented on jwt_authorizer_websocket_api_lambda_authorizer/src/authLambda.zip
Pls add as source file and let AWS SAM handle the packaging, e.g.
https://github.com/aws/aws-sam-cli-app-templates/tree/master/nodejs20.x/hello

2024-08-22 05:19 UTC, srajaw commented on jwt_authorizer_websocket_api_lambda_authorizer/README.md
> +```
it just shows default profile for aws cli

2026-07-23 08:15 UTC, marcojahn commented
This branch has become stale, closing. If you want to continue/update, please feel free to re-open.

2026-07-23 08:15 UTC, closed without merging