S3 notification event trigger Java-based AWS Lambda function
aws-samples/serverless-patterns pull request #2399
Opened 2024-07-31 03:05 UTC by dmahapatro

P144345160

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-31 22:07 UTC, yualexan commented
Thanks @dmahapatro for the quick turnaround.

@pputhran @julianwood Can you please help review or identify reviewers for this?

2024-08-02 16:40 UTC, seshubaws commented
Thank you @dmahapatro for adding this! Could you add an example-pattern.json file to this? Here's a [sample example-pattern.json](https://github.com/aws-samples/serverless-patterns/blob/main/_pattern-model/example-pattern.json).

2024-08-06 18:25 UTC, dmahapatro commented
@seshubaws Added `example-pattern.json`.

2024-08-13 23:42 UTC, seshubaws commented on s3-lambda-resizing-java/template.yaml
> +    Type: String
```suggestion
    Type: String
    # Pass your bucket name dynamically or change it here
    Default: my-source-bucket-name
```

2024-08-13 23:42 UTC, seshubaws commented on s3-lambda-resizing-java/template.yaml
> +    Type: String
```suggestion
    Type: String
    # Pass your bucket name dynamically or change it here
    Default: my-destination-bucket-name
```

2024-08-13 23:44 UTC, seshubaws commented on s3-lambda-resizing-java/README.md
> +  * Allow SAM CLI to create IAM roles with the required permissions.
```suggestion
  * Allow SAM CLI to create IAM roles with the required permissions.
      * Enter names for your source and destination S3 buckets. Make sure these are unique as S3 bucket names share a global namespace.
```

2024-08-16 12:57 UTC, ellisms requested changes

2024-08-16 12:57 UTC, ellisms commented on s3-lambda-resizing-java/README.md
> +# AWS Amazon S3 to AWS Lambda — Create a Java-based Lambda function that resizes images uploaded to S3
```suggestion
# Resizing images uploaded to Amazon S3 with AWS Lambda in Java
```

2024-08-16 12:57 UTC, ellisms commented on s3-lambda-resizing-java/README.md
> +- Modify the [events/s3_event.json](./ResizerFunction/src/test/resources) file to reflect the source bucket name and object key. Replace these values in the placeholders.
Can we default the object key to white_dog.jepg?

2024-08-16 12:57 UTC, ellisms commented on s3-lambda-resizing-java/README.md
> +- Run `mvn clean test`
Add changing directory to ./ResizerFunction

2024-08-16 12:57 UTC, ellisms commented on s3-lambda-resizing-java/README.md
> +
Add requirement for Java21

2024-08-16 13:30 UTC, dmahapatro commented
@ellisms Review comments are incorporated.

2024-08-16 21:07 UTC, ellisms commented
Thanks @dmahapatro. Adding this to the publishing queue.

2024-08-16 21:07 UTC, ellisms approved these changes

2024-08-21 12:36 UTC, merged