New pattern - S3 Lambda resizing image (python)
aws-samples/serverless-patterns pull request #2409
Opened 2024-08-02 21:10 UTC by seshubaws

*Issue #, if available:*

*Description of changes:*
Adding a pattern using the Python function code from this tutorial: https://docs.aws.amazon.com/lambda/latest/dg/with-s3-example.html and the template from this already existing serverless land pattern (Node version): https://github.com/aws-samples/serverless-patterns/tree/main/s3-lambda

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-08-08 10:49 UTC, ellisms commented
@seshubaws I started looking at this and need clarification on which directory should be used. The README indicates `s3-lambda`, but the files in your commit are `s3-lambda-resizing-python`. Which one should I use?

2024-08-08 21:25 UTC, seshubaws commented
Hi @ellisms thank you for taking a look at this! I fixed the naming disparity, they should all refer to `s3-lambda-resizing-python` now

2024-08-09 12:29 UTC, ellisms commented
Thanks @seshubaws . The Lambda function is producing the following error:
```
[ERROR] UnidentifiedImageError: cannot identify image file '/tmp/1e7deef4-6414-4718-ae10-b3397f311fbewhite_dog.jpeg'
Traceback (most recent call last):
  File "/var/task/app.py", line 21, in lambda_handler
    resize_image(download_path, upload_path)
  File "/var/task/app.py", line 9, in resize_image
    with Image.open(image_path) as image:
  File "/var/task/PIL/Image.py", line 3498, in open
    raise UnidentifiedImageError(msg)
```

2024-08-13 23:38 UTC, seshubaws commented
Thanks for catching! The photo for the test event was corrupted, I fixed it. Please test again at your earliest convenience.

2024-08-15 17:48 UTC, ellisms requested changes

2024-08-15 17:53 UTC, seshubaws commented on s3-lambda-resizing-python/README.md
> +    * Enter the desired AWS Region
I added that below "Enter names for your source and destination S3 buckets. Make sure these are unique as S3 bucket names share a global namespace."

2024-08-15 17:53 UTC, seshubaws commented on s3-lambda-resizing-python/README.md
> +    * Enter the desired AWS Region
I can move it up a line since they go together

2024-08-15 17:56 UTC, seshubaws commented on s3-lambda-resizing-python/template.yaml
> +      CodeUri: src/
the code is in `src/`

2024-08-15 18:12 UTC, seshubaws commented on s3-lambda-resizing-python/README.md
> +aws s3 cp './events/example.jpg'  s3://{SourceBucketName}
I think this comment was on an outdated readme, fixed now

2024-08-15 18:13 UTC, seshubaws commented on s3-lambda-resizing-python/template.yaml
> +                    Value: '.jpg'
Updated everything to be .jpeg

2024-08-15 18:14 UTC, seshubaws commented on s3-lambda-resizing-python/README.md
> +* The code assumes that the destination bucket exists and its name is a concatenation of the source bucket name followed by the string -resized
Removed this line, the dest bucket can be any name

2024-08-16 12:08 UTC, ellisms approved these changes

2024-08-16 14:58 UTC, merged