New serverless pattern - CloudFront to Lambda Function URL using OAC
aws-samples/serverless-patterns pull request #2454
Opened 2024-08-29 10:34 UTC by sshekghub

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-09-09 10:16 UTC, marcojahn requested changes

2024-09-09 10:16 UTC, marcojahn commented on cloudfront-lambdafunctionurl-oac-sam/LICENSE
File can be removed

2024-09-09 10:16 UTC, marcojahn commented on cloudfront-lambdafunctionurl-oac-sam/README.md
> +# Access your Lambda Function URLs securely using Amazon CloudFront Origin Access Control
```suggestion
# Amazon CloudFront Origin Access Control for AWS Lambda Function URL
```

2024-09-09 10:16 UTC, marcojahn commented on cloudfront-lambdafunctionurl-oac-sam/example-pattern.json
Getting multiple json parser errors, can you please check and fix?

2024-09-09 10:16 UTC, marcojahn commented on cloudfront-lambdafunctionurl-oac-sam/example-pattern.json
> +  "title": "Access your Lambda Function URLs securely using Amazon CloudFront Origin Access Control",
```suggestion
  "title": "Amazon CloudFront Origin Access Control for AWS Lambda Function URLl",
```

2024-09-10 12:23 UTC, sshekghub commented
Made the requested changes 1/ Removed License file 2/ Updated title in README as well as in pattern json file 3/ Fixed errors in pattern json file.

2024-09-20 14:43 UTC, marcojahn approved these changes

2024-09-20 14:45 UTC, marcojahn commented
Hello @sshekghub thank you for your contribution. The pattern will be merged to serverlessland.com soon.

2024-09-23 14:45 UTC, merged