New serverless pattern for cloudwatch metric streams to kinesis firehose
aws-samples/serverless-patterns pull request #2461
Opened 2024-09-02 12:41 UTC by kiranram

*Issue #, if available:*

*Description of changes:*
This new pattern creates CloudWatch Metric Streams, which is sent to Kinesis Firehose with S3 bucket as destination. In this pattern the region is set to eu-west-2 but can be configured. The implementation is in Terraform.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-09-05 09:06 UTC, biswanathmukherjee commented
Please add `example-pattern.json` as provided in the sample here: https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model

2024-09-05 09:31 UTC, kiranram commented
The example-pattern.json file has been added now.

2024-09-05 12:22 UTC, kiranram commented
Updated to Amazon Data Firehose

2024-09-06 06:41 UTC, biswanathmukherjee requested changes

2024-09-06 10:30 UTC, kiranram commented on cloudwatch-metric-streams-firehose-terraform/README.md
> +After deployment, launch an EC2 instance in eu-west-2 region, and after a few minutes the metrics data will appear in the S3 bucket.
The README file has been updated on how to use CLI to override the default region. This should allow having streams in any region as per the users choice.

The file is stored in Amazon S3 in GZIP format, so using gunzip should extract the contents. The default format for contents was set to Opentelemetry0.7, which has now been changed to JSON (human readable). The metrics written into these files are as per what has been configured in the IaC (main.tf), which can be altered/modified as per the requirements. In this example, there are 2 metrics (CPU utilization and NetworkOut) from EC2 (or RDS if provisioned) which appear in the files.

2024-09-06 10:30 UTC, kiranram commented on cloudwatch-metric-streams-firehose-terraform/example-pattern.json
> +      "linkedin": "https://www.linkedin.com/in/kiran-ramamurthy-a96341b/",
Updated with ID.

2024-10-07 13:29 UTC, merged