New serverless pattern - alb-ecs-bedrock-agents-cdk-dotnet
aws-samples/serverless-patterns pull request #2489
Opened 2024-10-11 20:29 UTC by tejasavora

*Issue #, if available:*
N/A

*Description of changes:*
## Description of changes:

This Pull Request implements an AI-powered travel service using AWS CDK with .NET. Key components and changes include:

1. **Bedrock Agent Integration**: Implemented an AI agent using Amazon Bedrock for natural language interactions with customers.

2. **Knowledge Base**: Created a vector database using Amazon OpenSearch Serverless to store and quickly retrieve travel information and policies.

3. **Action Groups**: Defined action groups for the Bedrock agent, including a flight search functionality.

4. **Lambda Functions**: Developed Lambda functions to handle specific tasks such as flight searches and data processing.

5. **ECS with Fargate**: Set up Amazon ECS with Fargate to host the main travel service application.

6. **Application Load Balancer**: Implemented an ALB to route incoming requests to the ECS tasks.

7. **CDK Stack**: Created a comprehensive CDK stack in .NET to define and deploy all AWS resources.

8. **API Schema**: Defined an API schema for the flight search functionality.

9. **Error Handling**: Implemented robust error handling and logging mechanisms.

10. **Documentation**: Added detailed README.md and example-pattern.json files to explain the solution architecture, deployment process, and testing procedures.

11. **Testing**: Included curl commands and instructions for testing the deployed service.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-11-01 14:00 UTC, marcojahn requested changes
Hi @tejasavora, thank your for your contribution. I've tested the code and it works. Could  you please review and fix the few requests for the readme file and architecture diagram I've added? TY

2024-11-05 22:07 UTC, tejasavora commented on alb-ecs-bedrock-agents-cdk-dotnet/README.md
> +## Architecture
Updated the diagram

2024-11-05 23:43 UTC, tejasavora commented on alb-ecs-bedrock-agents-cdk-dotnet/README.md
> +1. Use the agent to interact with the travel service:
Added Testing from Console instruction
Testing from console description and steps
Adding documents to S3 and syncing knowledge base

2024-11-05 23:43 UTC, tejasavora commented on alb-ecs-bedrock-agents-cdk-dotnet/README.md
> +## Testing
Added

2024-12-30 09:40 UTC, marcojahn approved these changes

2024-12-30 09:43 UTC, marcojahn commented
Hello @tejasavora, thank you for your contribution. Your pattern will be merged by a DA to serverlessland.com soon.

2025-01-06 10:51 UTC, merged