APIGW Websocket API Bedrock Streaming Rust CDK
aws-samples/serverless-patterns pull request #2505
Opened 2024-11-04 21:09 UTC by philcallister

This CDK application demonstrates a simple, serverless streaming approach to integrating Amazon Bedrock with AWS Lambda and Amazon API Gateway

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-12-02 18:31 UTC, philcallister commented
Hi @ellisms apologies for the missed documentation. Updated README to include `cross` dependency: `cargo install cross --git https://github.com/cross-rs/cross`

2024-12-02 23:59 UTC, ellisms requested changes

2024-12-02 23:59 UTC, ellisms commented
> Hi @ellisms apologies for the missed documentation. Updated README to include `cross` dependency: `cargo install cross --git https://github.com/cross-rs/cross`

Thanks, I successfully tested this. Just requesting a minor edit before I move forward.

2024-12-03 15:00 UTC, ellisms approved these changes

2024-12-03 15:01 UTC, ellisms commented
Thanks @philcallister . I'll add this to the publishing queue.

2024-12-10 15:57 UTC, merged