New serverless pattern: stream bedrock completions via appsync events websockets
aws-samples/serverless-patterns pull request #2508
Opened 2024-11-07 11:42 UTC by gbiagini97

*Issue #, if available:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-12-13 10:08 UTC, marcojahn requested changes
I am not able to deploy, running step 4 from deployement instructions (`npm run deploy`) results in an error:

```
11:01:18 AM | CREATE_FAILED        | AWS::AppSync::ApiKey           | ApiKey
API key must be valid for a minimum of 1 days. (Service: AWSAppSync; Status Code: 400; Error Code: ApiKeyValidityOutOfBou
ndsException; Request ID: 4c4651cb-809a-4c09-a27c-39f3645fa860; Proxy: null)
```

The current pattern is broken after 12.12.
```
  ApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt EventsApi.ApiId
      Description: Api Key for Events Api
      Expires: 1733989774
```

As the API_KEY can be only configured for up to 365 days [1] please add creation/update process do the deployment documentation, as otherwise the code will break (requiring users to debug) after 365 days.


[1] https://docs.aws.amazon.com/appsync/latest/devguide/security-authz.html#api-key-authorization

2024-12-13 10:08 UTC, marcojahn commented on appsync-events-bedrock-cdk/src/chat.ts
> +    // log event
can be removed

2024-12-13 10:08 UTC, marcojahn commented on appsync-events-bedrock-cdk/src/chat.ts
> +    // log env vars
can be removed

2024-12-13 10:08 UTC, marcojahn commented on appsync-events-bedrock-cdk/src/chat.ts
> +    //console.log(process.env)
can be removed

2024-12-13 10:08 UTC, marcojahn commented on appsync-events-bedrock-cdk/lib/appsync-events-bedrock-cdk-stack.ts
Can you remove double blank lines from the code?

2024-12-13 10:08 UTC, marcojahn commented on appsync-events-bedrock-cdk/lib/events-api-cfn.yaml
Can you remove double blank lines from the code?

2024-12-13 10:08 UTC, marcojahn commented on appsync-events-bedrock-cdk/src/chat.ts
Can you remove double blank lines from the code?

2024-12-13 10:08 UTC, marcojahn commented on appsync-events-bedrock-cdk/test/appsync-events-bedrock-cdk.test.ts
Can you remove double blank lines from the code?

2024-12-13 10:08 UTC, marcojahn commented on appsync-events-bedrock-cdk/utils/apigwRequest.ts
Can you remove double blank lines from the code?

2025-01-13 19:12 UTC, gbiagini97 commented
@marcojahn sorry for the late. I addressed your points and removed the components defined via plain CFN. Now it's CDK-only.

2025-03-18 09:04 UTC, marcojahn approved these changes
Hello @gbiagini97, 
thanks for your contribution. A serverless DA will merge your PR soon!

2025-03-19 10:49 UTC, merged