Philippewanner feature iot rule action lambda python cdk ts
aws-samples/serverless-patterns pull request #2510
Opened 2024-11-08 13:00 UTC by philippewanner

*Issue #, if available:*

Description of changes: This pattern shows how to integrate AWS Lambda with IoT core, using a rule and trigger another Lambda.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-12-13 10:20 UTC, marcojahn requested changes
Can you please change all CDK dependencies using v2 instead of v1. CDK v1 is end-of-life since 2023-06-01

```
❯ npm install
npm WARN deprecated @aws-cdk/cx-api@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/cloud-assembly-schema@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/core@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/aws-s3-assets@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/aws-autoscaling-common@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/assets@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/aws-codestarnotifications@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/aws-sqs@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/aws-efs@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/aws-sns@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/aws-signer@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/aws-codeguruprofiler@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/aws-ssm@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/aws-ecr-assets@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/aws-ecr@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/aws-kms@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/region-info@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/aws-applicationautoscaling@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/aws-logs@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/aws-s3@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/aws-events@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/aws-cloudwatch@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm WARN deprecated For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
npm WARN deprecated @aws-cdk/aws-iam@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
npm WARN deprecated
npm W [...]

2024-12-13 10:20 UTC, marcojahn commented on iot-lambda-pub-receiver-cdk/README.md
> +This pattern deploys one publisher AWS Lambda, which publishes a message in AWS IoT Core topic. The topic is watch by a rule which triggers an action when the condition is met. The action calls a AWS
```suggestion
This pattern deploys an AWS Lambda function, which publishes a message to an AWS IoT Core topic. The topic is watched by a rule which will trigger an action when the condition is met. The action calls an AWS Lambda function.
```

2024-12-13 10:20 UTC, marcojahn commented on iot-lambda-pub-receiver-cdk/README.md
> +Learn more about this pattern at Serverless Land Patterns: << Add the live URL here >>
Learn more about this pattern at Serverless Land Patterns: https://serverlessland.com/patterns/iot-lambda-pub-receiver-cdk

2024-12-13 10:20 UTC, marcojahn commented on iot-lambda-pub-receiver-cdk/package.json
> +    "source-map-support": "^0.5.21"
pls update using CDK v2 libraries, as CDK v1 has reached end of support 2023-06-01

2024-12-17 10:11 UTC, marcojahn requested changes

2024-12-17 10:11 UTC, marcojahn commented on iot-lambda-pub-receiver-cdk/lib/lambda-iot-cdk-stack.ts
> +    console.log(IOT_ENDPOINT)
Pls remove, outputs only a token, not resolved during deployment time (`${Token[TOKEN.49]}`)

2024-12-17 10:21 UTC, philippewanner commented
Console.log() removed.

2024-12-17 10:25 UTC, marcojahn commented
Hello @philippewanner,
thank you for your contribution. A serverless DA will merge your submission soon.
Regards,
Marco

2025-01-06 10:51 UTC, merged