New serverless pattern - EventBridge Scheduler to invoke Step Functions to get the List of Inactive Lambda functions
aws-samples/serverless-patterns pull request #2533
Opened 2024-12-11 20:50 UTC by sahilk225579

*Issue #, if available:*

*Description of changes:*

added all the required SAM template, lambda function code & state machine defination.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-12-30 10:26 UTC, marcojahn requested changes
###

2024-12-30 10:26 UTC, marcojahn commented on eventbridge-stepfunction-lambda-getfunctionstatus/README.md
> +# EventBridge scheduler to invoke step function to get the list of inactive lambda functions
```suggestion
# Amazon EventBridge Scheduler to invoke an AWS Step Function to get the list of inactive AWS Lambda functions
```

2024-12-30 10:26 UTC, marcojahn commented on eventbridge-stepfunction-lambda-getfunctionstatus/README.md
> +This pattern will create a one time schedule in EventBridge scheduler with state machine as target & invoke the lambda ListFunctions & GetFunction API using the SDK integration in step functions and
```suggestion
This pattern will create an Amazon EventBridge Scheduler rule targeting an AWS Step Function state machine. The Step Function invokes an AWS Lambda using `ListFunctions` and `GetFunctions` API using the SDK integration in Step Functions. It publishes the list of inactive functions to an Amazon SNS Topic.
```

2024-12-30 10:26 UTC, marcojahn commented on eventbridge-stepfunction-lambda-getfunctionstatus/README.md
> +7. **Imp** : Once the SNS topic & subscription is created, verify the subscription by clicking the 'Confirm subscription' link received on your email.
```suggestion
7. **Important** : Once the SNS topic & subscription is created, verify the subscription by clicking the 'Confirm subscription' link received on your email. 
```
"Imp" means "important"?

2024-12-30 10:26 UTC, marcojahn commented on eventbridge-stepfunction-lambda-getfunctionstatus/README.md
> +1. When the stack is deployed it creates a state machine, an eventBridge scheduler,a SNS topic with email subscription, a Lambda Function and required IAM roles.
```suggestion
1. When the stack is deployed it creates a state machine, an Event Bridge Scheduler, an SNS topic with email subscription, a Lambda function and required IAM roles. 
```

2024-12-30 10:26 UTC, marcojahn commented on eventbridge-stepfunction-lambda-getfunctionstatus/README.md
> +2. Event Bridge scheduler invokes the State machine on defined schedule, Default schedule invokes the state machine daily at 00::00 UTC with the below mentioned payload. Modify the schedule as per yo
```suggestion
2. Event Bridge Scheduler invokes the state machine with a defined schedule. The default schedule invokes the state machine daily at 00:00 UTC with the below mentioned payload. Modify the schedule as per your requirement.
```

2024-12-30 10:26 UTC, marcojahn commented on eventbridge-stepfunction-lambda-getfunctionstatus/README.md
> +3) In state machine, the 1st step is to get the list of all lambda functions in the current region using the ListFunctions API, ListFunctions API is called multiple times as it returns max 50 functio
```suggestion
3) In the state machine, the first step is to get the list of all Lambda functions in the current region using the ListFunctions API. The ListFunctions API is called multiple times as it returns a maximum of 50 function listed in a single API call, along with a NextMarker pagination parameter. Using the NextMarker token, the state machine retrieves a list of all the function ARNs.
```

2024-12-30 10:26 UTC, marcojahn commented on eventbridge-stepfunction-lambda-getfunctionstatus/README.md
> +4) Lambda Invoke Combine data Step : This a custom lambda function python script to create a combined json array of Lambda function ARN's retrieved in step 1.
```suggestion
4) Lambda Invoke Combine data Step : This a custom Lambda function python script to create a combined JSON array of Lambda function ARNs retrieved in step 1.
```

2024-12-30 10:26 UTC, marcojahn commented on eventbridge-stepfunction-lambda-getfunctionstatus/README.md
> +5) Map - Loop Functions State : In this state, GetFunction API is called for each Lambda ARN taken as input from previous step & status of each function is checked and appended to the output.
```suggestion
5) Map - loop functions state: In this state, the GetFunction API is called for each Lambda ARN taken as input from the previous step, and the status of each function is checked and appended to the output.
```

2024-12-30 10:26 UTC, marcojahn commented on eventbridge-stepfunction-lambda-getfunctionstatus/README.md
> +6) Filter Inactive Functions State : This filters out the Active functions from the Json array and passes only the Inactive functions list to the next step.
```suggestion
6) Filter inactive functions state: This filters out the active functions from the JSON array and passes only the list of inactive functions to the next step.
```

2024-12-30 10:26 UTC, marcojahn commented on eventbridge-stepfunction-lambda-getfunctionstatus/README.md
> +7) SNS Publish : List of Inactive functions is published to the SNS Topic.
```suggestion
7) SNS publish : List of inactive functions is published to the SNS Topic.
```

2024-12-30 10:26 UTC, marcojahn commented on eventbridge-stepfunction-lambda-getfunctionstatus/README.md
> +Copyright 2022 Amazon.com, Inc. or its affiliates. All Rights Reserved.
```suggestion
Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved.
```

2024-12-30 10:27 UTC, marcojahn commented
Hello @sahilk225579, I've requested a few changes. After applying the PR can be processed further.
TY

2024-12-30 12:49 UTC, sahilk225579 commented
added all the changes

2025-01-24 14:43 UTC, marcojahn approved these changes

2025-01-24 15:29 UTC, marcojahn commented
Hello @sahilk225579, thank you for your contribution. Your pattern will be merged by a serverless DA soon.

2025-01-27 10:46 UTC, merged