New serverless pattern - Serverless Messaging Redrive
aws-samples/serverless-patterns pull request #2543
Opened 2024-12-16 16:41 UTC by zalilias

*Description of changes:*
A serverless AWS solution for processing and fixing malformed messages using SQS queues and Lambda functions. This system automatically handles message validation, applies fixes where possible, and routes messages to appropriate queues based on their fixability. With built-in error handling and detailed logging, it provides a robust framework for message processing that can be easily extended for specific business needs.

The architecture uses AWS Lambda for processing, multiple SQS queues for message routing, and includes a dead-letter queue (DLQ) for messages requiring human intervention. Built with AWS SAM.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-12-16 17:54 UTC, benjymoses requested changes
You need to include a README.md with a detailed description of what this sample is, as well as deployment, testing, and deletion instructions.

You also need to include the `*pattern.json` file as per [the sample](https://github.com/aws-samples/serverless-patterns/blob/main/_pattern-model/example-pattern.json) adapted to your needs.

If any of the feedback / comments aren't clear, feel free to DM me offline to discuss and I can help point you in the right direction.

2024-12-16 17:54 UTC, benjymoses commented on serverless-message-processing/functions/processor/requirements.txt
> +jsonschema==4.17.3
Is this being used directly?

2024-12-16 17:54 UTC, benjymoses commented on serverless-message-processing/template.yaml
> +      Timeout: 29
Is this always going to be adequate as this scales out? Consider parameterising this value (for both functions) and including more comments about the when it's declared at the top of this YAML doc describing when people might want to increase it.

2024-12-16 17:54 UTC, benjymoses commented on serverless-message-processing/template.yaml
> +      Timeout: 29
Same comment about parameterisation as above

2024-12-16 17:56 UTC, benjymoses commented
@ellisms I've been helping @zalilias with this and have done a first cursory review. It's worth letting him parse through that and integrate / reject my feedback before you do your review so you're making good use of your time.

2025-01-15 11:39 UTC, benjymoses reviewed
Hey @zalilias thanks for bearing with me doing this next pass for you. This has come a long way but before we send to @ellisms for review I think there's a few more bits to go through. 

As usual, if any of my comments don't make sense or you're not sure, just ping me 👍

2025-01-15 11:39 UTC, benjymoses commented on serverless-message-processing/example-pattern.json
@zalilias you need to rename the file to be in line with the name of your pattern and replace the contents of the template / example with information about your pattern.

2025-01-15 11:39 UTC, benjymoses commented on serverless-message-processing/README.md
> +# Send Message
Good idea to include a copy of the API contract, but It would be nice to see commands that users can use in their terminal as an example `curl https://${endpoint}/message....` with the relevant params to send a sample message.

2025-01-15 11:39 UTC, benjymoses commented on serverless-message-processing/README.md
> +## Deployment
Likely to come up in @ellisms review, but we typically include a statement on users being responsible for spinning up / tearing down / paying for resources in their own AWS accounts. We'd also typically talk about having the AWS CLI installed and configured as a pre-requisite to using SAM. Take a look at some other SAM examples to get a feel for the norm.

2025-01-15 11:39 UTC, benjymoses commented on serverless-message-processing/README.md
> +3. Processor Lambda handles messages
Would include that this Lambda function **polls** the main queue using [Event Source Mappings (ESMs)](https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventsourcemapping.html) and handles the messages. Include links to docs / blogs / posts where they can build understanding.

2025-01-15 11:39 UTC, benjymoses commented on serverless-message-processing/README.md
> +4. Failed messages route to DLQs
If you're going to use terse statements in a numbered or bulleted list, it would be good to include a more full explanation alongside them. In this context what's a "failed message"? See if you can go a level deeper to explain what's going on as it may be confusing to somebody unfamiliar with the pattern or certain service features, like DLQ.

2025-01-15 11:39 UTC, benjymoses commented on serverless-message-processing/README.md
> +## Key Features
These may make sense to you in the context of being the author, but somebody coming to this as a new idea will need each of these explaining.

2025-01-15 11:39 UTC, benjymoses commented on serverless-message-processing/README.md
> +## Adaptation Points
If you want to keep a terse list then you might need a sentence or 2 before the list to explain what you mean by Adaptation Points (earlier you called it extensible, pick one way of describing this concept).

2025-01-15 11:39 UTC, benjymoses commented on serverless-message-processing/README.md
> +## Note
What's this section, or is it a note to self that should have been deleted?

2025-01-15 11:39 UTC, benjymoses commented on serverless-message-processing/functions/decision_maker/app.py
> +            if can_fix_email(message) and not re.match(EMAIL_PATTERN, message['email']):
Your function `can_fix_email()` seems to itself make a call (line 57) to `fix_email()` and then you call the same function again on the next line (line 98). Why does it need to be called twice? Seems like you have functions with mixed responsibilities.

2025-01-15 11:39 UTC, benjymoses commented on serverless-message-processing/functions/decision_maker/app.py
I couldn't see where you were making use of the original failure message from the main queue to decide which branching logic to take. Using your "email fix" as an example.

1. Invalid email address provided in payload to API GW
2. Message stored durably in SQS main queue
3. Lambda function polls the queue and attempts to use that malformed email address to some imagined down-stream service.
4. Downstream service returns an error due to malformed email.
5. Your main Lambda poller would send a response to SQS for that message and give a failure reason (shared enum of failures maybe), in this example "MALFORMED_EMAIL".
6. When your decision maker picks that up, I presumed that it would switch through those failure reasons and apply the relevant fix.

For this example it's fine to just use the email scenario as 1 example with the view that the enum can be extended and more failure scenarios might be encountered.

2025-01-15 11:39 UTC, benjymoses commented on serverless-message-processing/template.yaml
>  Description: Serverless message processing architecture
This description doesn't match what you're actually doing - this isn's just about message processing, it's about attempted automated failure re-drive.

2025-01-15 11:39 UTC, benjymoses commented on serverless-message-processing/template.yaml
> +      Recommended ranges:
What does "heavy" mean to the user? Isn't this ultimately dependent on how computationally expensive the operation would be? Perhaps in the context of a demo pattern think instead of suggesting 2 values with the lower as the default given it's just a sample and not meant to be production grade.

There would be an expectation that if a customer wanted to fork this and use it themselves that they'd do their own due diligence on memory sizing for their use case. Likely using Lambda Power Tuning.

2025-01-15 11:39 UTC, benjymoses commented on serverless-message-processing/template.yaml
> +  DecisionMakerMemorySize:
Same comments as for ProcessorMemorySize

2025-01-15 11:39 UTC, benjymoses commented on serverless-message-processing/template.yaml
> +  DecisionMakerTimeout:
This parameter has all of the same constraints as the one above for the same reasons (they're Lambda functions). I'd collapse in to one parameter called `LambdaTimeout` and make use of it for both functions. Make sure to update the first line of the description.

2025-01-15 11:39 UTC, benjymoses commented on serverless-message-processing/template.yaml
>        Runtime: python3.9
Python 3.9 is 4 years old now, should we not be defaulting to the current LTS as this is a newly published asset? 3.12 seems like a reasonable default.

2025-02-17 14:40 UTC, zalilias commented
Many thanks for all of your recommendations @benjymoses, apologies for the delay in getting this done from my end. I've implemented the changes into my existing code and hopefully should be good to be published soon 🚀

2025-02-26 10:08 UTC, zalilias commented
Thanks for your support on this @benjymoses ! I'll look to submit my architecture this week

2025-02-26 13:34 UTC, ellisms commented
@benjymoses Sure, I'll add it to my list.
@zalilias Can you resolve the conversations you've taken care of? It'll make it easier for me to review. Thanks!

2025-02-28 15:37 UTC, zalilias commented
Thanks @ellisms, I've resolved the majority now, other than powertools which I can add in.

2025-03-06 19:47 UTC, ellisms commented
Hi @zalilias , I'm working on the review and testing. I came across the following error in the decision function, that I don't think is expected:
```
[ERROR] UnboundLocalError: cannot access local variable 'original_message_id' where it is not associated with a value
Traceback (most recent call last):
  File "/var/task/app.py", line 160, in lambda_handler
    logger.error(f"Error processing message {original_message_id}: {str(e)}")
```

2025-03-06 21:22 UTC, ellisms requested changes

2025-03-06 21:22 UTC, ellisms commented on serverless-message-processing/functions/decision_maker/app.py
> +            if 'remediation' in message:
This could be another case for the ReportBatchItemFailures feature. With that feature, you'd only be receiving actionable items.

2025-03-20 16:55 UTC, ellisms requested changes

2025-03-20 16:55 UTC, ellisms commented on serverless-message-processing/README.md
> +    cd serverless-patterns/serverless-messaging-redrive
```suggestion
    cd serverless-patterns/serverless-message-redrive
```

2025-03-20 16:55 UTC, ellisms commented on serverless-message-processing/example-pattern.json
> +        "image": "link-to-your-photo.jpg",
Please add a publicly-accessible image.

2025-03-20 16:56 UTC, ellisms commented
Hi @zalilias - I re-tested and everything tested OK. Just requesting 2 minor edits. Thanks!

2025-04-07 10:45 UTC, zalilias commented
Hi @ellisms , added in those 2 changes. Thanks!

2025-04-08 13:21 UTC, ellisms approved these changes

2025-04-08 13:21 UTC, ellisms commented
Thanks @zalilias I'll add this to the publishing queue.

2025-04-23 09:09 UTC, merged

2025-04-23 10:25 UTC, benjymoses commented
Congrats @zalilias and thanks for the efforts reviewing @ellisms !

2025-04-23 10:57 UTC, zalilias commented
Thank you for all of your mentorship + support in my TFC onboarding process and with this sample @benjymoses . I really appreciate it and I'm excited to see this within serverlessland!

Many thanks for your review on this sample @ellisms !