new serverless pattern - rekognition-s3-detectlabels-python
aws-samples/serverless-patterns pull request #2568
Opened 2024-12-25 10:32 UTC by abilashkumar

*Issue #, if available:*

*Description of changes:*
This is a new PR created for a new serverless pattern that involves S3, Eventbridge, Lambda and Rekognition deployed using SAM that detects labels in an image.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-12-30 15:39 UTC, marcojahn requested changes
Hello @abilashkumar,
I've reviewed your PR and requested a few changes, can you please check/update?
TY

2024-12-30 15:39 UTC, marcojahn commented on rekognition-s3-detectlabels-python/README.md
> +aws s3api put-object --bucket <INPUT_BUCKET_NAME>> --key <IMAGE_FILE> --body /path/to/your/<IMAGE_FILE>
```suggestion
aws s3api put-object --bucket <INPUT_BUCKET_NAME> --key <IMAGE_FILE> --body /path/to/your/<IMAGE_FILE>
```

2024-12-30 15:39 UTC, marcojahn commented on rekognition-s3-detectlabels-python/README.md
> +This pattern demonstrates how to create an S3 bucket which when uploaded with an object invokes a Lambda function through EventBridge. The function detect labels in an image through Amazon Rekognitio
```suggestion
This pattern demonstrates how to create an Amazon S3 bucket that triggers an AWS Lambda function via Amazon EventBridge upon object upload. The Lambda function detects labels in an image using Amazon Rekognition. The Lambda function is built using Python.
```

2024-12-30 15:39 UTC, marcojahn commented on rekognition-s3-detectlabels-python/README.md
> +The Cloudformation template creates 2 S3 buckets (source and destination buckets) along with a Lambda function (Python) and an EventBridge event. The Lambda function is triggered by the EventBridge w
```suggestion
The CloudFormation template creates two Amazon S3 buckets (source and destination) along with an AWS Lambda function (written in Python) and an Amazon EventBridge event. The Lambda function is triggered by EventBridge, which listens for object uploads in the S3 source bucket. The Lambda function makes a `DetectLabels` API call to Amazon Rekognition to detect labels in an image and stores the output in the destination S3 bucket.
```

2024-12-30 15:39 UTC, marcojahn commented on rekognition-s3-detectlabels-python/README.md
> +Upload the file (document/image) to the input S3 <STACK_NAME>-input-bucket-<AWS_ACCOUNTID> bucket via the console or use the PutObject API call below:
```suggestion
Upload the file (document/image) to the input S3 `<STACK_NAME>-input-bucket-<AWS_ACCOUNTID>` bucket via the console or use the `PutObject` API call below:
```

2024-12-30 15:39 UTC, marcojahn commented on rekognition-s3-detectlabels-python/README.md
> +
The output of the operation can be downloaded from the output S3 bucket `<STACK_NAME>-output-bucket-<AWS_ACCOUNTID>`.

2024-12-30 15:39 UTC, marcojahn commented on rekognition-s3-detectlabels-python/README.md
> +## Cleanup
As we are using SAM for deployment, `sam delete` is appropriate but buckets need to be emptied (manually) before.
Pls update the `delete the stack` section.

2025-01-02 11:01 UTC, abilashkumar commented on rekognition-s3-detectlabels-python/README.md
> +
Made the change

2025-01-02 11:02 UTC, abilashkumar commented on rekognition-s3-detectlabels-python/README.md
> +## Cleanup
Updated

2025-01-24 14:30 UTC, marcojahn approved these changes

2025-01-24 14:37 UTC, marcojahn commented
Hello @abilashkumar, thank you for your contribution. Your pattern has been reviewed and will be merged by a serverless DA soon.

2025-01-27 10:41 UTC, merged