New serverless pattern - okta-eventbridge-lambda
aws-samples/serverless-patterns pull request #2573
Opened 2024-12-30 21:24 UTC by ragibmahsan

*Issue #, if available:*

*Description of changes:* New pattern submission for Okta System Log Events to Lambda and CloudWatch

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2025-01-23 13:35 UTC, ellisms commented
Hi @ragibmahsan Thanks for the submission. Before I start reviewing, I'd like to make a directory structure change since I foresee additional SaaS integrations being created.
Can you update the PR to include the following directory structure (from root):
`/eventbridge-partner-sources/1-okta/cdk-python/<your files>`

Goal is to model this after the eventbridge-api-destinations directory: https://github.com/aws-samples/serverless-patterns/tree/main/eventbridge-api-destinations

2025-01-30 19:17 UTC, ragibmahsan commented
I updated the structure

2025-02-03 14:32 UTC, ellisms requested changes
Hi @ragibmahsan, requesting a few changes after review.

2025-02-03 14:32 UTC, ellisms commented on eventbridge-partner-sources/1-okta/cdk-python/README.md
> +    cd okta-eventbridge-lambda
```suggestion
    cd eventbridge-partner-sources/1-okta/cdk-python
```

2025-02-03 14:32 UTC, ellisms commented on eventbridge-partner-sources/1-okta/cdk-python/README.md
> +3. From the command line, use AWS CDK to deploy the AWS resources for the pattern as specified in the app.py file. A command-line argument is needed to deploy the CDK stack, "oktaEventBusName". This
```suggestion
3. From the command line, use AWS CDK to deploy the AWS resources for the pattern as specified in the app.py file. A command-line argument is needed to deploy the CDK stack, "oktaEventBusName". This argument is the name of the **SaaS event bus** associated with your Okta [partner event source](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-saas.html).
```

2025-02-03 14:32 UTC, ellisms commented on eventbridge-partner-sources/1-okta/cdk-python/README.md
> +The command should have create a response.json file in your directory. If you open this file, you see the output of the Lambda function.
```suggestion
The command creates a response.json file in your directory. If you open this file, you see the output of the Lambda function.  
```

2025-02-03 14:32 UTC, ellisms commented on eventbridge-partner-sources/1-okta/cdk-python/README.md
> +You cannot put events on the Okta event bus, only Okta can publish events to this event bus. To test that the EventBridge rules deployed by this pattern were successfully deployed, follow these instr
```suggestion
Only Okta can publish events to the event bus. To test the EventBridge rules deployed by this pattern, follow these instructions: 
```

2025-02-03 14:32 UTC, ellisms commented on eventbridge-partner-sources/1-okta/cdk-python/README.md
> +You should see a green box appear that says "Sample event matched the event pattern." This means that the rule will successfully route incoming events to the AWS Lambda function.
```suggestion
A successful test results in a  "Sample event matched the event pattern." message. This means that the rule will successfully route incoming events to the AWS Lambda function. 
```

2025-02-03 14:32 UTC, ellisms commented on eventbridge-partner-sources/1-okta/cdk-python/app.py
> +            runtime=_lambda.Runtime.PYTHON_3_8,
Python 3.8 is in deprecation. Bump to at least 3.12.

2025-02-04 18:30 UTC, merged